### ISSUE TITLE
Is the QSep@xnorm really needed?

### ISSUE THREAD

**Issue by sgibb** [lgatto/pRoloc#102]
The current implementation of the `QSep` class contains the `xnorm` slot. While being small in size (memory usage) its information is IMHO redundant because it could be easily and fast computed by `x/diag(x)`, e.g. `qsep` could be implemented as follows:

```r
qsep <- function(object, norm = TRUE) {
    stopifnot(inherits(object, "QSep"))
    if (norm) object@x/diag(object@x)
    else object@x
}
```

**Comment by lgatto** [comment]
It is a space/computation trade-off. I waste more memory, but you need to do a (short) computation every time the normalised data is accessed. In the grand scheme of things, both gains/losses are negligible here.

**Comment by sgibb** [comment]
Correct, I am thought that computation of `xnorm` would be more rare event than data storing and an easier data structure would be beneficial. But as you said it isn't really important here. Feel free to close the issue.
