### ISSUE TITLE
The tutorial link is 404

### ISSUE THREAD

**Issue by ab604** [lgatto/pRoloc#115]
https://lgatto.github.io/pRoloc/articles/pRoloc-tutorial.html

**Comment by lgatto** [comment]
Thank you for the report. The file names has indeed been changed.

Did that old URL come from the README.md file or the webpage, of did you spot it somewhere else.

**Comment by ab604** [comment]
Hi,

Thanks for fixing it. It was the one highlighted in yellow below in the README.md:
[cid:image001.png@01D41D47.8DC553B0]

All the best,

Alistair

**Comment by lgatto** [comment]
Ok, thank you!
