### ISSUE TITLE
Cholesky decomposition fix

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#124]
@ococrook - I saw the `cholesky-fix` branch. Thank you. 

Do you think this warrants a warning, or would a simple message not suffice. Also, whether it's a message or warning, could you refer the user to the documentation, and add a paragraph with a bit of explanation.

**Comment by ococrook** [comment]
Yes, a message is probably sufficient. Should I replace warning(...) with message(...)?

When you refer to documentation - do you mean the rd file or the vingette (or Both)?

**Comment by lgatto** [comment]
Yes, use `message()`.

Re documentation, the `rd` file is enough, especially as users will be directed to it when the fix kicks in.

**Comment by ococrook** [comment]
great, pull request made!

**Comment by lgatto** [comment]
Closing, as PR #125 has been merged.
