### ISSUE TITLE
Control grid presence in plot2D

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#128]
As per popular demand, provide an option to not add the grid in `plot2D`. 
```r
plot2D(..., grid = TRUE)
plot2D(..., grid = FALSE)
```
If this is indeed the preferred way, one could also complete drop it, and call `grid()` manually after `plot2D`

```r
plot2D(...)
grid()
```
cc @lmsimp

**Comment by lmsimp** [comment]
@ococrook :-)

**Comment by lgatto** [comment]
Please cast your vote for either
- `grid` argument with default value `TRUE` (thumbs up this comment :+1: )
- no `grid` at all (thumb down this comment :-1:)

I don't see the point of having a `grid = FALSE` default, as typing `grid = TRUE` as parameter in `plot2D` is longer than typing `grid()` after the function.

**Comment by lmsimp** [comment]
The default should still be `grid = TRUE`
