### ISSUE TITLE
Not able to run phenoDisco in pRoloc

### ISSUE THREAD

**Issue by azmal786** [lgatto/pRoloc#137]
Hi, 
I am trying to perform the localisation of the sub-cellular compartment in my dataset. but in between, I am getting this error stating that the dataset contains less than >6 markers, however it matched to more than 6.

**Error report:**
Error in phenoDisco(hl, GS = 10, times = 10, fcol = "markers") :
Not enough markers to run phenoDisco: Require > 6 markers per classes

Kindly suggest how to solve the problem
Thank you for your support.

**Comment by lgatto** [comment]
The message says exactly what the problem is: you need more markers. 

Please do read the documentation and vignette to help yourself running your analyses.
