### ISSUE TITLE
Updates to pRolocmarkers

### ISSUE THREAD

**Issue by Charl-Hutchings** [lgatto/pRoloc#151]
Opening an issue because @lmsimp and I would like to add some updated marker sets to pRolocmarkers and are wondering the best way to go about doing this. 

Our initial thoughts are to leave the current marker sets there for back compatibility and reproducibility of previous analyses but to add a number of new marker sets. Our motivation is firstly to provide some useful new marker sets that are not in pRoloc (but have been published and are publicly available) and secondly to provide v2 of older marker sets in which we will update the compartment names to be consistent across marker sets (potentially based on GO term names) and identifiers to be consistent too (UniProt accessions rather than gene names, as is the case for some currently in pRolocmarkers).

What would be the easiest/most suitable way to get started with this? Any thoughts/input appreciated.

**Comment by lgatto** [comment]
Updating markers should be high on the list, indeed. 

- Is the format (i.e. named character) still suitable for your needs?

If yes, what about updating the `pRolocmarkers()` function and add a `version` argument, that by default would have the version of the latest markers (say `version = 2`), and users could the older markers with `version = 1`.

The implementation would be simple: Add new marker `rds` files in `inst/extdata`, and call them `marker2_hsap.rds`, ... so that based on that version number, the appropriate files would be loaded in `pRolocmarkers()`.

**Comment by Charl-Hutchings** [comment]
I think that the format still works. The idea of versioning sounds like a good way to go, particularly with keeping the older marker sets and maintaining transparency. 

One final thing that I'd like to add in would be explicit references for published marker sets. As well as adding some new manually curated lists, I wanted to add some other lists that are publicly available in the supplementary of various papers. Currently, when you print

`pRolocmarkers()`

you get...

7 marker lists available:
Arabidopsis thaliana [atha]:
 Ids: TAIR, 543 markers
Drosophila melanogaster [dmel]:
 Ids: Uniprot, 179 markers
Gallus gallus [ggal]:
 Ids: IPI, 102 markers
Homo sapiens [hsap]:
 Ids: Uniprot, 872 markers
Mus musculus [mmus]:
 Ids: Uniprot, 937 markers
Saccharomyces cerevisiae [scer_sgd]:
 Ids: SGD, 259 markers
Saccharomyces cerevisiae [scer_uniprot]:
 Ids: Uniprot Accession, 259 markers


Would it be worthwhile adding `Ref` underneath the `Ids` line of each marker set, so that we can have references be explicit. Currently, the help page states: "The markers have been contributed by various members of the Cambridge Centre for Proteomics, in particular Dr Dan Nightingale for yeast, Dr Andy Christoforou and Dr Claire Mulvey for human, Dr Arnoud Groen for Arabodopsis and Dr Claire Mulvey for mouse. In addition, original (curated) markers from the pRolocdata datasets have been extracted (see pRolocdata for details and references)".  I think if we start adding more published marker sets, we should be more explicit so that people cite appropriately.

Thoughts?

**Comment by lmsimp** [comment]
> One final thing that I'd like to add in would be explicit references for published marker sets.

I like this idea. I had a quick look at the [code](https://github.com/lgatto/pRoloc/blob/ad9af3a7b34fc4bf9d189df1609d8fafba38bf25/R/pRolocmarkers.R#L47C1-L49C40) and looks like it would be easy enough to print out a DOI under the IDs. 

But where would this information be stored? In the .rds with the markers? We could perhaps have a list of two named characters, one for the markers, one for the DOI? Or the DOI could be encoded in the name of the marker.rds? We could also just add it to the help file? @lgatto 

> update the compartment names to be consistent across marker sets (potentially based on GO term names)

I'm not sure what the best approach is for compartment naming. I agree it would be worthwhile to make all the compartment names consistent across makers (where possible). Essentially, everyone ends up doing this themselves manually when wanting to compare datasets.

**Comment by Charl-Hutchings** [comment]
I agree re. making decisions on other groups' markers - I wouldn't feel comfortable doing this. Perhaps we can do consistency in terms of naming obvious ones e.g., "ER" vs "er" vs "Endoplasmic Reticulum" and "Mitochondria" vs "Mitochondrion", but not changing any compartments as such

**Comment by lgatto** [comment]
> One final thing that I'd like to add in would be explicit references for published marker sets.

I think these would need to be handled with their own marker rds files. 

```
pRolocmarkers() ## defaults to the latest list across multiple species
pRolocmarkers(version = "2") ## same as above
pRolocmarkers(version = "1") ## first version
pRolocmarkers(version = "author2024") ## markers used in Authors et al. (2024)
```

The general marker list would provide markers for multiple species, as we do now, while the paper lists would most likely only provide a list for a single species, but that's OK. 

We could add an optional DOI in the rds and display it, but I think the easiest would be to add this information in the documentation. We could either document everything in `pRolocmarkers.Rd` as we do now, or have paper-specific manual pages. 

If the above looks right, then I'll have a look at re-factoring the code and make a suggestion to accommodate these changes.

As for harmonisation, good luck. If this is important, then complementing marker names with GO terms would be the ideal, but I don't think this is worth the effort.

**Comment by lmsimp** [comment]
> We could add an optional DOI in the rds and display it, but I think the easiest would be to add this information in the documentation. We could either document everything in pRolocmarkers.Rd as we do now, or have paper-specific manual pages.

I am inclined to agree that adding a DOI and explicit reference to the documentation is enough.
The documentation could be improved and we could be a bit more explicit than we are currently with who has generated each marker list and where they come from (adding a DOI here). 

> If the above looks right, then I'll have a look at re-factoring the code and make a suggestion to accommodate these changes.

I think this is perhaps not worth the work if it's in the documentation.

**Comment by lgatto** [comment]
> If the above looks right, then I'll have a look at re-factoring the code and make a suggestion to accommodate these changes.

I meant for general updates, not for the DOI part. Will wait to see if @Charl-Hutchings is OK with my suggestion above and suggest a plan.

**Comment by Charl-Hutchings** [comment]
@lgatto I think the general plan sounds good. 

Re. DOI, I agree that as long as the documentation is more explicit than it is currently and we have the author names in the marker set names, all should be ok.

**Comment by lgatto** [comment]
I have updated the `pRolocmarkers()` [function](https://github.com/lgatto/pRoloc/commit/5ec5574a7001d47368b2e8755ff236c12945a339) to support different versions. I will want to add some checks for the supported versions, but you should be able to add new markers lists by adding new rds files in `inst/extdata` that all share a specific prefix, and define the version and that prefix in the `switch()` statement at the top of `pRolocmarkers()`.

**Comment by Charl-Hutchings** [comment]
@lgatto Thank you for doing that. I have added 14 marker lists to version 2 with all `.rds` files having the prefix `"marker2_"`. All necessary changes have been made in `pRolocmarkers.R`, including making version 2 the default. Everything is working fine on my local system. 

Unfortunately, when I execute `R CMD build pRoloc` on my local system, I get an error due to problems with re-building some of the `pRoloc` vignettes. Here is the specific error message:

SUMMARY: processing the following files failed:
  ‘v01-pRoloc-tutorial.Rmd’ ‘v02-pRoloc-ml.Rmd’
  ‘v03-pRoloc-bayesian.Rmd’ ‘v04-pRoloc-goannotations.Rmd’
  ‘v05-pRoloc-transfer-learning.Rmd’

Error: Vignette re-building failed.
Execution halted

@lmsimp mentioned that this is likely due to dependence on `biomaRt`.

**Comment by lgatto** [comment]
Thank you @Charl-Hutchings - could you send a PR, please?

The issue is fixed, and you'll need the latest pRolocdata version (from github, pushed yesterday on Bioc).

**Comment by lgatto** [comment]
Thank you @Charl-Hutchings - I have added you as a contributor in the DESCRIPTION file.

**Comment by lmsimp** [comment]
Now I’m confused 😂 did you not add the human list CSD curated?
