### ISSUE TITLE
plot2D unit test

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#30]
Write a `plot2D` unit test that compares (using md5sum for example) two image files, one template saved in ./inst/extdata and a newly created image.

**Comment by lgatto** [comment]
The [`EBImage`](http://bioconductor.org/packages/release/bioc/html/EBImage.html) is to be used for this.

**Comment by lgatto** [comment]
Closing for now, as I don't think it is easily doable.

**Comment by sgibb** [comment]
Currently I reconsider this problem but could not find a satisfactory answer. That's why I asked on SO now: http://stackoverflow.com/questions/30246789/how-to-test-graphical-output-of-functions

**Comment by lgatto** [comment]
Done in 95293df3256a22600e68d583a3f473ac06ade22b

**Comment by lgatto** [comment]
The [`vdiff`](https://github.com/r-lib/vdiffr) package seems to be a reasonable option here.
