### ISSUE TITLE
add parallelisation options to svmOptimisation?

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#36]
Currently if we want 100 times we run something like this -

```r
data(dunkley2006)
opt <- svmOptimisation(dunkley2006, times = 100)
```
Could we add something to allow use of `bplapply` which is called inside the function?

e.g. If I have 4 cores available I would do something like this
````r
x <- c(25, 25, 25, 25)
opt <- bplapply(x, function(z) svmOptimisation(fusion2013cmb, times = z), BPPARAM=MulticoreParam(4L))
opt <- combine(opt)
```

**Comment by lgatto** [comment]
The problem with adding this is that we could not use a random seed, unless this is done with special parallel RNG infrastructure. I don't think this is essential (other things take more time), so closing now.
