### ISSUE TITLE
Replace unique(getMarkers) with getClasses function

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#41]
Replace unique(getMarkers) with getClasses function to ensure that order is preserved when generating a character vector or organelle classes in the data

**Comment by lgatto** [comment]
I see the following two possible changes.
```sh
$ grep unique * | grep getM
machinelearning-functions-knntl.R:    if (!identical(sort(unique(getMarkers(primary, fcol, verbose = FALSE))),
machinelearning-functions-knntl.R:                   sort(unique(getMarkers(auxiliary, fcol, verbose = FALSE)))))
```
@lmsimp could you check and either confirm or refute here, or commit change.

**Comment by lgatto** [comment]
@lmsimp - can we close this?
