### ISSUE TITLE
Clarify use of 'unknown' proteins in vignettes

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#48]
There may be some confusion from a biological point of view when we use the term' unknown' to describe proteins that are 'unlabelled' in our analysis. We should clarify to biologists that in our code unknown is used to describe instances that are left unlabelled, and this does not necessarily mean that they have unknown location in databases and elsewhere.

**Comment by lgatto** [comment]
This has actually been in the vignette for quite some time (I just now added 'unlabelled'). 

>  As can be seen above, some proteins are labelled \texttt{"unknown"}, defining non marker proteins. This is a convention in many \Biocpkg{pRoloc} functions. Missing annotations (empty string) will not be considered as of unknown localisation; we prefer to avoid empty strings and make the absence of known localisation explicit by using the \texttt{"unknown"} tag. This information will be used to separate marker and non-marker (unlabelled) proteins when proceeding with data visualisation and clustering (sections \ref{sec:viz} and \ref{sec:usml}) and classification analysis (section \ref{sec:sml}).
