### ISSUE TITLE
colours

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#51]
My preferred palette below. Would be nice to add this somewhere.

lisacols <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00",
              "#FFD700", "#A65628", "#F781BF", "#999999", "#333333",
              "#00CED1", "#276419","#FDAE6B","#A50F15", "#00008A", 
              "#8E0152", "#CD8C95", "#66C2A5", "#6A51A3","#EEAD0E", 
              "#0000FF", "#CDB5CD", "#CDBE70", "#9ACD32", "#CD6090",
              "#CD5B45", "#B0C4DE", "#808000", "#8B795E", "#483D8B")

**Comment by lgatto** [comment]
Now available in version 1.9.2 (commit `4ebc08b20495732cdfd0ed64c1c5623564fa5356`):

```r
getLisacol()
setLisacol() ## same as 
setStockcol("lisacol")
```
