### ISSUE TITLE
output of getPredictions

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#59]
Currently the output of `getPredictions` is a `character` of length `ncol(object)`. I think it would be nice if the output of this function was an updated `MSnSet` instance with a column appended to the `fData` slot, as is the case with `xxxClassification`. Then one can use `plot2D` or `pRolocVis` to examine their results. What do you think @lgatto?

**Comment by lgatto** [comment]
Ok, good idea. This will however need to wait after this release. Prefer not to make such a change to the interface just before the release.

**Comment by lmsimp** [comment]
I have updated this and put in branch "threshold-functions"

**Comment by lmsimp** [comment]
Ready to move to master after new release

**Comment by lgatto** [comment]
```
> ## 50% top predictions per class
> ts <- orgQuants(res, fcol = "svm")
Error in quantile.default(X[[i]], ...) : 
  argument "t" is missing, with no default
Calls: orgQuants ... tapply -> tapply -> lapply -> FUN -> FUN -> quantile.default
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  21: .handleSimpleError(function (e) 
     {
         e$calls <- head(sys.calls()[-seq_len(frame + 7)], -2)
         signalCondition(e)
     }, "cannot coerce type 'closure' to vector of type 'character'", quote(.Method(..., 
         sep = sep, collapse = collapse)))
  
  testthat results ================================================================
  OK: 48 SKIPPED: 0 FAILED: 1
  1. Error: getPredictions with different thresholds 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by lgatto** [comment]
Could you also bump to version 1.11.1 and update the NEWS file.

**Comment by lmsimp** [comment]
Done

**Comment by lmsimp** [comment]
There is an issue I have come across. The function `orgQuants` calculated class-specific quantile thresholds on the **unlabelled** data. If there are **no** new assignments for some organelles in the unknowns, the threshold is returned as NA. See,

```{r} 
library('pRoloc')
library('pRolocdata')
data(dunkley2006)
dunkley2006 <- ksvmClassification(dunkley2006, cost = 4)
aa <- orgQuants(dunkley2006, fcol = "ksvm", t = .5)
```
     ER lumen   ER membrane         Golgi Mitochondrion       Plastid            PM 
    0.3432242     0.9121086     0.7426773     0.3555516     0.4148445     0.1692141 
     Ribosome           TGN       vacuole 
           NA     0.1647195            NA 

Now, this produces an error of course when `aa` is passed to `getPredictions`. So, should I somewhere check for any NA's and set as 1?

What do you think?

This has broken my classification app.

**Comment by lgatto** [comment]
I would keep the `NA` values. 1 would be wrong, unless you also use the markers (for all classes). I think `getPredictions` should handle `NA`s.

**Comment by lgatto** [comment]
> I would keep the `NA` values. 1 would be wrong, unless you also use the markers (for all classes). I think getPredictions should handle `NA`s. 

I see why you mention 1: `getPredictions` could handle the `NA`s by using a fake threshold that is bigger than any existing classification score (1 if strict comparison, or `Inf` to be on the safe side).

**Comment by lmsimp** [comment]
Yes, this was my thinking. I would maybe suggest we do not allow NA's to be an input threshold to `getPredictions` as it doesn't really make sense to have a NA cutoff. I would force the input threshold `t` for `getPredictions` to be numeric. We could add an option to `orgQuants` something like `.naAs1 = TRUE` so that this doesn't happen. What do you think?

**Comment by lgatto** [comment]
Why not consider `NA` that are passed as input to `getPredictions` for what they are, i.e. thresholds that are not available (for whatever reason, in particular the one that you highlighted). If a threshold is not available, nothing is predicted. That sounds all logic to me and does not require any additional parameters. One could imagine a warning message to inform the user. (In terms of implementation, you could set `NA` values to `Inf`, I suppose.)

By the way, is the input to `getPredicitons` a named numeric, and names must match exactly `getMarkerClasses(x)` after ordering?

**Comment by lmsimp** [comment]
> Why not consider NA that are passed as input to getPredictions for what they are, i.e. thresholds that are not available (for whatever reason, in particular the one that you highlighted). If a threshold is not available, nothing is predicted. That sounds all logic to me and does not require any additional parameters. One could imagine a warning message to inform the user. (In terms of implementation, you could set NA values to Inf, I suppose.)
Okay

> By the way, is the input to getPredicitons a named numeric, and names must match exactly getMarkerClasses(x) after ordering?
Yes

**Comment by lgatto** [comment]
Once all sorted (see also error above), you can merge the branch into master (expect a minor conflict in DESCRIPTION and NEWS)

**Comment by lmsimp** [comment]
Fixing tests now. May need to ask you about a few other things tomorrow before I merge.

**Comment by lmsimp** [comment]
One using `pRolocVis_classify` may find it very strange that when selecting their cutoffs with the top quantile slider in the app, which applied class-specific quantile thresholding, gets a resultant class thresholds that contains NA's. Maybe we should have some explanation in documentation to explain this behaviour?

**Comment by lgatto** [comment]
Yes, it should be explained that the thresholds are calculated on the assigned non-markers, which might be an empty set. There might be an opportunity for a `withMarkers = [TRUE|FALSE]` parameter (with default `FALSE`).

**Comment by lmsimp** [comment]
I have just seen this function `minClassScore` which as far as I can see is the same as the new `getPredictions`? If this is now redundant should we remove it?

**Comment by lgatto** [comment]
Could you deprecate `minClassScore` (see `?deprecated` for details), and after the next release, we will defunct it (see `?defunct`). 
I think that `getPredictions` is a better name, and that returning an `MSnSet` is the best thing to do, both in terms of consistency and user-friendliness.

**Comment by lmsimp** [comment]
@lgatto Deprecating `minClassScore` according to these [instructions](https://www.bioconductor.org/developers/how-to/deprecation/). 

I am a little confused about the documentation for deprecated functions. I have called `.Depreciated(getPredictions)` inside the old `minClassScore` function, and removed documentation above the function for Roxygen and added a defunct man [here](https://github.com/lgatto/pRoloc/blob/threshold-functions/man/defunct.R) as per instructed.

What am I missing? Why does this documentation not link with `minClassScore`, I have added `minClassScore` as an alias in the doc.

**Comment by lgatto** [comment]
`defunct.R` should be `defunct.Rd`. See also Deprec[i]ated typo.

**Comment by lmsimp** [comment]
Thank you!

**Comment by lmsimp** [comment]
I think we are almost ready to merge. Can you pull branch, build, check and install too, all is good from my side.

**Comment by lgatto** [comment]
You might have forgotten to push your latest changes.

**Comment by lmsimp** [comment]
Pushed
