### ISSUE TITLE
pRolocVisMethods

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#61]
- Vector storing name of available methods, `pRolocVisMethods`
- Function `.validpRolocVisMethod` to check if `matrix` or valid character

**Comment by lmsimp** [comment]
Have added `pRolocVisMethod` and `.validpRolocVisMethod` in [plotting.R](https://github.com/lgatto/pRoloc/commit/a175d9bb93c858522c706925054be1280a91b163) I will now add this check to my functions and `plot2D`.

**Comment by lmsimp** [comment]
@lgatto Just seen you already have `plot2Dmethods` I think `pRolocVisMethod` is better as its more general

**Comment by lmsimp** [comment]
@lgatto Do you think `scree` should be a method? For the vis apps if `scree` is selected do you think I should by default plot the first two PCs? Or not allow `scree` as and option for the Shiny Apps?

**Comment by lgatto** [comment]
> Just seen you already have plot2Dmethods I think pRolocVisMethod is better as its more general

```r
plot2Dmethods <- c(plotVisMethods, "scree")
```

**Comment by lmsimp** [comment]
Great idea. Will do this.
