### ISSUE TITLE
Explanation of Markers Matrix

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#62]
Somewhere in the vignette we need a section to explain that the `markers` stored in the feature data can either be a `matrix` or a `character vector`. Default if it's a matrix of markers is `Markers`. See `mrkVecToMat` and friends.

**Comment by lmsimp** [comment]
@lgatto Did we decide that is is okay to call `mrkVecToMat` inside new vis apps if input is not a matrix?

**Comment by lgatto** [comment]
Yes, doing that transparently is fine, as long as the user's data is not modified.

**Comment by lmsimp** [comment]
One issue, all the feature data columns in the new hyperlopit data, have names that begin with capitals (see `data(hyperLOPIT2015)` and `fvarLabels(hyperLOPIT2015)` in `pRolocdata`). This is very annoying for using `mrkMatToVec`. There is the situation where I have a column called `Markers` which is a matrix, but I wish to plot the column `SVM` using my app, now, if I call `mrkMatToVec` with `vfcol = "SVM"` then I get an error as there is already `Markers`, I can specify a name for `mfcol` e.g. `mfcol = "xxx"` and plot that, this is all invisible and not seen my user, what would you suggest I call `mfcol` for these cases?

> Yes, doing that transparently is fine, as long as the user's data is not modified.
When I call `mrkMatToVec` as discussed above, the users data is not altered as we do not return `object`. To be extra safe I can create a new `MSnSet` i.e. a copy of `object` but with the new `Markers` matrix appended, and use that for the interactive plotting, if in the future you envisage returning the original `object`?

**Comment by lgatto** [comment]
> What would you suggest I call mfcol for these cases?

```r
mfcol <- paste0("Markers", format(Sys.time(), "%a%b%d%H%M%S%Y"))
```

> To be extra safe I can create a new MSnSet i.e. a copy of `object`

That's not needed. Just wanted to make sure it's not returned. Not sure about the future; no plans to return at this stage.
