### ISSUE TITLE
plot2D method = "none"

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#67]
Allow `method = "none"`, or similar, where no transformation is performed. This will allow us to pass a re-mapped `MSnSet` where re-mapped data is in the `exprs` slot.

**Comment by lgatto** [comment]
See branch `none` - could you have a go and let me know what you think.

**Comment by lmsimp** [comment]
Looks good

**Comment by lgatto** [comment]
Merge into master a93e6fac7da64845addd7a8409a8867e65713ffd
