### ISSUE TITLE
plot = FALSE with plot2D

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#68]
When saving the output of `plot2D` to an object, if the argument `plot = FALSE` is executed and any of the mirror arguments are passed the PC's are not updated accordingly. When `plot = TRUE` is used however the PC's are saved fine. See code chunk below for example.

```r
library('pRoloc')
library('pRolocdata')
data("dunkley2006")

## regular PCs
head(plot2D(dunkley2006))

## mirrored X
head(plot2D(dunkley2006, mirrorX = TRUE, plot = TRUE)

## when plot = FALSE, PCs not updated with mirrorX argument     
head(plot2D(dunkley2006, mirrorX = TRUE, plot = FALSE)
```

**Comment by lgatto** [comment]
Fixed in commit `d4d63837903c851009b588f1fe98a8c2c1c2fc30`. Thanks for reporting.
