### ISSUE TITLE
highlightOnPlot and FeaturesOfInterest requests

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#69]
When creating a `FeaturesOfInterest` object would it be possible to have the default `fnames` as `featureNames(object)`? Currently, `fnames` is an object of class `character` which must be one of `fvarLabels`.

Would it also be possible to pass `featureNames(object)` instead of `foi` to `highlightOnPlot`?

**Comment by lgatto** [comment]
> When creating a FeaturesOfInterest object would it be possible to have the default fnames as featureNames(object)? Currently, fnames is an object of class character which must be one of fvarLabels.

Now, if `labels = TRUE`, `featureNames(object)` of `rownames(object)` (if `object` is a `matrix`) are used as labels (see c28fefbde7226635b8836b9781ac7caa823abf26).

**Comment by lgatto** [comment]
> Would it also be possible to pass featureNames(object) instead of foi to highlightOnPlot?

Done, in commit bcc583c0f82a92f1df2743d82fb0e70eaf49c726.
