### ISSUE TITLE
getLisaCol()

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#70]
@lgatto Can I remove grey from the above colour palette? The colour gets lost with the default grey for unknowns. Would like to change this before regenerating figures for documentation.

**Comment by lgatto** [comment]
Your colours, your decision.

**Comment by lmsimp** [comment]
Will it break anything you can think of?

**Comment by lgatto** [comment]
Don't know, but most likely, yes ;-) May be wait for that change once you have merge the compare branch, so it would be easier to roll back in case anything breaks.

**Comment by lmsimp** [comment]
I have changed `getLisaCol`. Now to deprecate `getLisaCol` and make `getStockCol`. Rename `getStockCol` to `getOldStockCol`.

**Comment by lgatto** [comment]
Done in 6187b253b26923d58fb33f9c57e192f8bbf6efce.

**Comment by lgatto** [comment]
and pushed to Bioc.
