### ISSUE TITLE
rename addGoMarkers to addGoAnnotations

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#76]
In
- code
- NAMESPACE
- documentation 
- unit tests

and the rename the added feature col to `goAnnotations`;

and rename vignette accordingly.

**Comment by lgatto** [comment]
There is also `minMarkers`, `maxMarkers`, ....

**Comment by lmsimp** [comment]
Done, what about 'filterMinMarkers' 'max' and 'subset'?

**Comment by lgatto** [comment]
Have you also updated `minMarkers`/`maxMarkers`?

I would leave all these at they are for now. I wanted to rename the GO bit as these are annotations from GO, not markers yet, and we don't want to say they can all be used as markers without some level of curation. All the other functions are meant to be used on markers.

**Comment by lmsimp** [comment]
Just checking and then will push. I haven't updated `min/maxMarkers` and friends. Shall I update NEWS? Probably no need as the last entry says it all?

**Comment by lgatto** [comment]
Just update the NEWS item with new function name.
