### ISSUE TITLE
New maxMarkers function?

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#81]
What about writing a new function which given a `MSnSet`, `fcol` and maximum number of markers `n` per class will return an updated `MSnSet` with a new feature data column containing the same organelle classes in the original `fcol` but with no more than `n` markers per class (which are sampled randomly from each organelle class).

This would be useful for the the `knntlOptimisation` runs but I am worried this may give the wrong message with regards to organelle markers...

**Comment by lgatto** [comment]
This is a bit ironic, but yes, good idea. In the examples and unit test, use `set.seed` as an illustration and to control the result.

**Comment by lmsimp** [comment]
Maybe this should be called `reducedMarkers` or similar

**Comment by lgatto** [comment]
Yes, fine by me.

**Comment by lgatto** [comment]
Closing, but happy to consider a PR.
