### ISSUE TITLE
Add convex hulls to a PCA plot

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#86]
cc: @dan-night-89

To use the new function, you will need to install `pRoloc` from `github` (commit 5aebfb556c0e916487bb5a9ca8776a8970e27f49 or later)

```r
BiocInstaller::biocLite("lgatto/pRoloc")
```

It is private, so you'll need to access it with `:::`

```r
plot2D(x)
pRoloc:::addConvexHulls(x)
```
Here's how it looks for the `hyperLOPIT` and `E14TG2aS1` data

![convexhulls1](https://cloud.githubusercontent.com/assets/384198/17851285/127d3abe-6859-11e6-9cb5-2dd605cbc08c.png)

![convexhulls2](https://cloud.githubusercontent.com/assets/384198/17851393/a4fdca8e-6859-11e6-8e62-e07b0ce3a0fa.png)

**Comment by dan-night-89** [comment]
Thanks @lgatto it works!

**Comment by dan-night-89** [comment]
I do not seem to be able to close this issue, so I will leave it to you.
