### ISSUE TITLE
pRoloc fails to install

### ISSUE THREAD

**Issue by prvst** [lgatto/pRoloc#90]
Hi, I'm running an Ubuntu 16.04.01 machine, with R version 3.3.2.

When I try to install pRoloc, I get the following message:

`> biocLite("pRoloc", dependencies = TRUE)`
`* installing *source* package ‘pRoloc’ ...`
`** libs`
`g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/home/felipevl/R/RcppArmadillo/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pRoloc.cpp -o pRoloc.o`
`g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o pRoloc.so pRoloc.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR`
`installing to /home/felipevl/R/pRoloc/libs`
`** R`
`** data`
`** inst`
`** preparing package for lazy loading`
`Error : object ‘predict.plsda’ is not exported by 'namespace:caret'`
`ERROR: lazy loading failed for package ‘pRoloc’`
`* removing ‘/home/felipevl/R/pRoloc’`
`The downloaded source packages are in`
`	‘/tmp/RtmpYHQqFA/downloaded_packages’`
`Warning message:`
`In install.packages(pkgs = doing, lib = lib, ...) :`
`  installation of package ‘pRoloc’ had non-zero exit status`

**Comment by lgatto** [comment]
This has been addressed in devel and released, but will take 24 hours before becoming available. You can install from github. Or, alternatively, downgrade `caret` to 6.0-71 (it's a simple change in the latest 6.0-72 that breaks `pRoloc`).

Closing this issue, but feel free to re-open it if necessary.

(Note that there's another error that just popped up #89 that I hope to be able to fix tonight or tomorrow).

**Comment by prvst** [comment]
thanks
