### ISSUE TITLE
plotDist x-axis labelling

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#91]
Currently, channels on the x-axis are labelled sequentially from `1:ncol(msnset)`  we ideally want the labels to be the `sampleNames`, this is what one expects

**Comment by lgatto** [comment]
There's a `fractions` argument that can be used. I agree thought that the default should use `sampleNames`. In the meantime, what about
```r
plotDist(hyperLOPIT2015, fractions = "TMT.Reagent")
```
