### ISSUE TITLE
highlightOnPlot and mirrorX mirrorY

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRoloc#93]
I thought this got fixed in #79 so need to check

From Claire:

Hi Laurent and Lisa,

further to our chat yesterday, I just wanted to let you know that there is an issue with highlightOnPlot and mirrorX even in normal pRoloc (not just the GUI). I have attached a pic of the result I get when plotting the same group of proteins on the dataset, with and without flipping it with mirrorX.

Maybe I am doing something wrong. This is what I did:

ecol = c(3:22)

eset <- readMSnSet2("LPS_THP_set1and2_090117.txt", ecol, fnames = "Accession", sep = "\t")

eset = addMarkers(eset, markers = "Markers_for_classification_271016.csv", mcol = "markers")

par(mfrow = c(1,2))

prots <- c("O14579", "P35606-2", "P48444", "P53618", "P53621", "P61923", "Q9Y678")

foiA <- FeaturesOfInterest(description = "coatomers", fnames = prots, object = eset)

plot2D(eset, fcol = "markers", main = "LPS 12hr THP-1")

highlightOnPlot(eset, foiA, fcol = "markers")

plot2D(eset, fcol = "markers", main = "LPS 12hr THP-1", mirrorX = T)

highlightOnPlot(eset, foiA, fcol = "markers")

... result attached...(highlighted proteins are not flipped!)

I need to flip the plot, to keep it the same orientation as the unstimulated plot. I have tried using the Compare App, but it seems to complain that I don't have the same number of quant columns, and also, I don't want to just plot the common features - I want to keep the full dataset for both. I will try to play a bit more with the Compare App now.

Thanks very much! Apologies for bothering you and I hope this is the right email address for CPU :)

Best wishes

Claireerror with mirrorX.tiff

**Comment by lgatto** [comment]
`highlightOnPlot` needs to be passed `args = list(mirrorX = TRUE)`.
