### ISSUE TITLE
Review t-SNE algorithm

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#96]
- [x] Update t-SNE using `Rtsne`
- [ ] Document evaluation of perplexity.

**Comment by lgatto** [comment]
Note that there was in a big in `tnse`, documented [here](https://gist.github.com/mikelove/74bbf5c41010ae1dc94281cface90d32), which has been fixed in version 0.1.3.

**Comment by kbarylyuk** [comment]
Hi Laurent,
being very excited about how well my data are visualised by t-SNE, I've tried to use the new t-SNE implementation in plot2D, but something does not work.

I've installed the development version of pRoloc as follows:

> source("http://bioconductor.org/biocLite.R")
> biocLite("lgatto/pRoloc")

Then used the following syntax for running plot2D, which returned the an error message:

> result_tSNE_new <- plot2D(ToxoLOPIT_12combined, method = "t-SNE")
Loading required namespace: Rtsne
Error in .data[, dims] : incorrect number of dimensions

Shall I pass any additional arguments?

**Comment by lgatto** [comment]
Fixed now, sorry for the inconvenience. 

Let me know how it goes and then I will close the issue.

**Comment by kbarylyuk** [comment]
Tested the updated function - it works and does it much faster than the original function did. However, the map it produces looks quite a bit different from the old one. I guess it might be due to the approximation that Rtsne uses to speed up the calculation. I am going to look into the behavior and output of the old Vs. new t-SNE implementation in a more systematic way.
Thanks for making this update.

**Comment by lgatto** [comment]
I will document how to use t-SNE in the vignette, hopefully later today. Will post here.

**Comment by lgatto** [comment]
I have added a couple of paragraphs to the tutorial 

![2017-03-07-172630_1203x743_scrot](https://cloud.githubusercontent.com/assets/384198/23669595/a68b1854-035c-11e7-83d0-c9da2f72b911.png)

**Comment by lgatto** [comment]
Closing issue. @kbarylyuk feel free to re-open it if there's anything that needs to be fixed or discussed.

**Comment by kbarylyuk** [comment]
Hi Laurent,
I've been playing with t-SNE visualisation of my toxoplasma LOPIT data and discovered that the new version (Rtsne) does not output maps of a similar (visual) quality as the old one (tsne) did. I think the difference is in how the function pre-processes data. The old tsne function has a parameter called whiten that is set to TRUE by default. If I switch it to FALSE the resulting map usually looks more similar (less visually appealing) to those produced with Rtsne. Rtsne does not have whitening step built in, but it does have an option to pre-process data with PCA. See example maps attached (all produced with set.seed(16)).
Out of all cases, my data look best with the old tsne function and whitening set to TRUE. I manually looked into some putative clusters and they seem to make sense from the biological point of view. So the question is, how do I make Rtsne produce equally nice-looking maps?
[ToxoLOPIT_Rtsne_PCAon.pdf](https://github.com/lgatto/pRoloc/files/845206/ToxoLOPIT_Rtsne_PCAon.pdf)
[ToxoLOPIT_Rtsne_PCAoff.pdf](https://github.com/lgatto/pRoloc/files/845208/ToxoLOPIT_Rtsne_PCAoff.pdf)
[ToxoLOPIT_tsne_WhitenOn.pdf](https://github.com/lgatto/pRoloc/files/845210/ToxoLOPIT_tsne_WhitenOn.pdf)
[ToxoLOPIT_tsne_WhitenOff.pdf](https://github.com/lgatto/pRoloc/files/845212/ToxoLOPIT_tsne_WhitenOff.pdf)

**Comment by kbarylyuk** [comment]
I've tried your suggestion, and I think it looks better than the old Rtsne result. For instance, a putative cluster of conoid proteins that I manually identified from the old tsne map, looks good on this map, too (black empty circles).

![toxolopit_rtsneafterpcacenteredscaled](https://cloud.githubusercontent.com/assets/13316340/24000643/b902aa94-0a53-11e7-9c31-e8b7a9ee0147.png)

Do I understand it correctly that centring and scaling the data in addition to PCA is equivalent to whitening operation from the old tsne function?

Many thanks for your help!

**Comment by lgatto** [comment]
Centering is done by default inside `Rtsne`, but not scaling. The code chunk above does it explicitly.

In `tsne`, the data is scaled, then centered. There is another transformation, whitening, that removes correlation between variables, but I am unsure how it compares to `Rtsne` more generally. 

From your feedback, it seems that scaling and centering is suitable for your data, and that whitening (if absent from `Rtsne`) is not as critical. Currently, the code in `Rtnse` doesn't support scaling, but this can be easily fixed with a patch. I submitted on a couple of weeks ago that was incorporated, so I am now considering sending another one to support scaling.

**Comment by lgatto** [comment]
@kbarylyuk - just to let you know that the latest `pRoloc` version (currently only on github, in Bioc devel in 24 hours or so) not supports centring and scaling (by default) when doing t-SNE.
