### ISSUE TITLE
Plot3d Documentation | permission denied

### ISSUE THREAD

**Issue by Kohze** [lgatto/pRoloc#97]
While adding the  Plot3D testthat code with "visualTest"  #87  in analogy to Plot2D I tried to reproduce the
 `?Plot3D() ` example. Copying the code, a ftp access denied error appears in the download part.

![screenshot_14](https://cloud.githubusercontent.com/assets/16598797/23823835/17c45088-066b-11e7-870e-8463454bfded.png)

![screenshot_13](https://cloud.githubusercontent.com/assets/16598797/23823825/0837fc28-066b-11e7-8a57-7fc0381d458a.png)

 (note: the last line says "couldnt authenticate to the server - permission denied")

Update:

when trying it again it says: "
> mzf <- pxget(px1, i)
Downloading 1 file
TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML already present. "

but then the next step  ` ms <- openMSfile(mzf)` fails because the file is probably not loaded and the type of mzf is "character".

**Comment by lgatto** [comment]
The first error must either be on your side, or a temporary issue on the PRIDE server side. I checked and it works. 

The next issue results from the presence of a file names `TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML` in your working directory, which stops the function to download it. But as the file is corrupted (as per prior error), it can't be loaded with `openMSfile`. 

Finally, `visualTest` is unfortunately not the solution I hoped it would be. It doens't seem to work reliable across platforms, hence I wouldn't necessarily suggest to write such a test. I still hope finding a cross platform way to test figures...

**Comment by Kohze** [comment]
well if we compared svg images by their vectors it should probably platform independend. Otherwise would it be sufficient to test a direct precursor of the plot?

**Comment by lgatto** [comment]
I tried several options a few years ago, but I don't remember whether svg was part of the them (although I suspect it was). It would be great if it worked.

What do you mean precursor of the plot? Data? No, that wouldn't be sufficient, because it's the output, the actual figure, that I would like to test.

**Comment by Kohze** [comment]
One example of precursor plot code in case of ggplot2 (but should also work for other plots). 

```
p <- ggplot(mpg, aes(cyl, hwy)) + geom_point()
deparse(p)
```
or direct:

`deparse(ggplot(mpg, aes(cyl, hwy)) + geom_point())
`

output:

![screenshot_18](https://cloud.githubusercontent.com/assets/16598797/23835803/ddec53b6-076d-11e7-9b55-f64c61b0eb51.png)

It shows all values that ggplot2 takes to create the final plot and at the same time tests if ggplot2 still works as intended.  I assume we can get similar code from deparsing the plot2d and plot3d functions.

**Comment by lgatto** [comment]
`plot2D` invisibly returns a matrix with the data in 2 dimensions. This is however of no use. As far as I know, base plotting doesn't return any *plotting* objects.

**Comment by Kohze** [comment]
ok then svgs are the only option left (if any) because R is frequently changing the engine (R 3.3.3 is using the plot engine 11, R 4.0 is using the plot engine 12) and therefore a image to image test will quickly be broken again. If we just had something to intercept it just before the plot engine it would be probably worth its own package. I will close this issue for now.
